services:
  web:
    container_name: novitatis_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production