import {
  projects as projectsEn,
  projectCategories as projectCategoriesEn,
  type Project,
} from "./projects-content";
import huData from "./projects-content.hu.json";
import type { Locale } from "./i18n/config";

// Hungarian translations of the 28 case studies, keyed by slug (generated by the
// translation workflow into projects-content.hu.json). We merge the HU text over
// the English data at read time and keep the structural fields (slug, id,
// pillarSlug, year, cover, pdfs) in English so routing and filtering still work.
const HU = huData as Record<string, Partial<Project>>;

const CATEGORY_LABELS_HU: Record<string, string> = {
  all: "Összes",
  consulting: "Tanácsadás és stratégia",
  education: "Oktatás és mentorálás",
  development: "Fejlesztés és digitalizáció",
};

export function getProjects(locale: Locale): Project[] {
  if (locale !== "hu") return projectsEn;
  return projectsEn.map((p) => {
    const t = HU[p.slug];
    if (!t) return p;
    return {
      ...p,
      ...t,
      // never let translated copy override the keys that drive routing/filtering
      slug: p.slug,
      id: p.id,
      pillarSlug: p.pillarSlug,
      year: p.year,
    } as Project;
  });
}

export function getProjectCategories(locale: Locale) {
  if (locale !== "hu") return projectCategoriesEn;
  return projectCategoriesEn.map((c) => ({
    ...c,
    label: CATEGORY_LABELS_HU[c.slug] ?? c.label,
  }));
}
