// AUTO-GENERATED by scripts/build_references.py — do not edit by hand.
// Source: ../Novi honlap/public_speaking_events_lista.xlsx ("Events (EN)" tab).
// Regenerate with: npm run refs

export type RefType =
  | "talk" | "panel" | "podcast" | "exhibition" | "workshop" | "publication";

export type Reference = {
  id: string;
  slug: string;
  title: string;
  summary: string;
  description: string;
  type: RefType;
  typeLabel: string;
  date: string;
  year: string;
  location: string;
  organizer: string;
  tags: string[];
  audience: string;
  language: string;
  videoUrl: string;
  pressUrl: string;
  quote: string;
  cover: string;
  photos: string[];
  imageAlt: string;
  seoTitle: string;
  seoDescription: string;
  featured: boolean;
  order: number;
  size: "lg" | "wide" | "tall" | "sm";
};

export const referenceCategories: { slug: string; label: string }[] =
[
  {
    "slug": "all",
    "label": "All"
  },
  {
    "slug": "talk",
    "label": "Talks"
  },
  {
    "slug": "panel",
    "label": "Panels"
  },
  {
    "slug": "podcast",
    "label": "Podcasts"
  },
  {
    "slug": "exhibition",
    "label": "Exhibitions"
  },
  {
    "slug": "workshop",
    "label": "Workshops"
  },
  {
    "slug": "publication",
    "label": "Publications"
  }
];

export const references: Reference[] = [
  {
    "id": "8",
    "slug": "stay-visible-in-the-age-of-ai-talk",
    "title": "Stay visible in the age of AI – talk (ÜKFP / VVVA)",
    "summary": "It's no longer the customer searching – AI searches on their behalf. The talk shows how businesses get found in the age of AI search: in 2026, 45% of consumers use an AI tool to find a local company, up from just 6% a year earlier (a 7.5x jump). Delivered at the Veszprém County Enterprise Development Foundation event.",
    "description": "Adam Schmutz's talk at the event “AI-based colleagues and the fight for visibility”, organized by the Veszprém County Enterprise Development Foundation (VVVA) within the Business Environment Development Program (ÜKFP) for SME leaders in Fejér and Veszprém counties. The central question: “How do your customers find you when they no longer search — but AI searches for them?” It builds on fresh data: in 2026, 45% of consumers use an AI tool to find a local business (up from just 6% a year ago – a 7.5x increase; BrightLocal 2026), AI Mode search is three times longer than classic Google search, and Google AI Mode reaches 1 billion monthly active users. Schmutz introduces the new consumer type, the “Asker”, who expects a direct answer from AI rather than a list, and the guest's 6-step, predominantly digital customer journey. The new competition: not who appears first among Google's 10 results, but whether AI mentions you at all. The talk gives concrete, free, Hungarian-market-tailored steps to grow digital/AI visibility (GEO). Other speakers: Dr. Kitti Hiezl and Dr. Eszter Madarasz (University of Pannonia).",
    "type": "talk",
    "typeLabel": "Talk",
    "date": "2026-05-26",
    "year": "2026",
    "location": "Veszprém, Hungary (ÜKFP / VVVA event)",
    "organizer": "“AI-based colleagues and the fight for visibility” – Business Environment Development Program (ÜKFP); organizer: Veszprém County Enterprise Development Foundation (VVVA)",
    "tags": [
      "AI search",
      "GEO",
      "generative engine optimization"
    ],
    "audience": "SME leaders, entrepreneurs (Fejér and Veszprém counties), tourism providers",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“The question used to be who appears first among Google's 10 results. Now it's: does AI mention you at all when someone asks?” In 2026, 45% of consumers already use an AI tool to find a local business – up from just 6% a year ago.",
    "cover": "/images/manual-covers/stay-visible.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "Stay visible in the age of AI – talk | Adam Schmutz",
    "seoDescription": "Adam Schmutz's talk: how do customers find you in the age of AI search? 45% already use AI to find a local business – what to do so AI mentions you too.",
    "featured": true,
    "order": 3,
    "size": "lg"
  },
  {
    "id": "9",
    "slug": "hungary-data-driven-tourism-ntak-smart-tour-cotes-darmor",
    "title": "Hungary's real-time tourism analytics and AI",
    "summary": "English-language international talk at the 3rd meeting of the Smart Tour (Interreg Europe) project in Brittany, France: Hungary's real-time, data-driven tourism system (NTAK/NTDSC) as a European best practice – daily automatic data from 95,000+ accommodations and AI forecasting, representing the Visit Balaton 365 DMO.",
    "description": "Adam Schmutz's (Digital Tourism Expert, Visit Balaton 365 DMO) English-language talk at the 3rd Steering Group meeting and thematic workshop of the Smart Tour (Interreg Europe) project in Côtes d'Armor (Perros-Guirec, France). Delivered in the pitch block of the “Tourism statistics and indicators” workshop, as one of five international speakers (representing the Lake Balaton Development Coordination Agency; other pitchers: Heraklion, Côtes d'Armor, Jesolo, Tuzla). It presents Hungary's real-time, data-driven tourism ecosystem as a European best practice. Starting point: most destinations don't know how many guests will arrive next week. The National Tourism Data Supply Center (NTDSC / NTAK) solves this: providers must register, and data flows in automatically, daily, without manual reporting, directly from their software (via free NTO software or API integration). More than 95,000 accommodations supply daily data; on top of this runs AI forecasting (occupancy, guest arrivals) and the “Accommodation Compass” analytics tool. The talk covers benefits (whitening the sector, tax revenue, more efficient marketing, competitiveness) and future plans: provider-level data + dynamic pricing support for everyone, full sector coverage, and cross-border European data exchange. It closes with five conditions for adoption: sector-wide common will, a legal mandate, starting with provider data, building other sources on top, and a national OR regional scale.",
    "type": "talk",
    "typeLabel": "Talk",
    "date": "2026-05-20",
    "year": "2026",
    "location": "Perros-Guirec, Côtes d'Armor, Brittany, France",
    "organizer": "Smart Tour (Interreg Europe) – 3rd Steering Group Meeting & Thematic Workshop, Côtes d'Armor (19–22 May 2026); thematic workshop: Tourism statistics and indicators",
    "tags": [
      "data-driven tourism",
      "NTAK",
      "NTDSC"
    ],
    "audience": "European destination management organizations (DMOs), tourism decision-makers, policymakers",
    "language": "EN",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“The technology is available and not complicated — the hardest parts are sector-wide common will and a legal mandate.” In Hungary, 95,000+ accommodations supply daily, automatic data to the NTAK/NTDSC system – providers don't have to lift a finger.",
    "cover": "/images/manual-covers/smart-tour.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "Hungary's data-driven tourism (NTAK) – international talk | Adam Schmutz",
    "seoDescription": "Adam Schmutz at the Smart Tour Interreg meeting (Côtes d'Armor): Hungary's NTAK/NTDSC real-time tourism data and AI forecasting as a European best practice.",
    "featured": true,
    "order": 6,
    "size": "sm"
  },
  {
    "id": "7",
    "slug": "tiszazug-2035-cserkeszolo-tourism-strategy-talk",
    "title": "Cserkeszőlő tourism strategy",
    "summary": "A region that is not short on attractions but disorganized and under-packaged: repositioning the tourism of Tiszazug (13 settlements) based on primary research and four international strategy models (Saba, Plan T, Linz, Perth). Delivered at the “Crown and Sword” event in Cserkeszőlő.",
    "description": "Adam Schmutz's talk at the event “Tourism opportunities of businesses in local economic development”, organized by the “Crown and Sword” Rural and Regional Development Foundation at the Baghy-Szinyei Merse Manor in Cserkeszőlő. The talk (official slide title: “Tiszazug 2035 – Repositioning regional tourism in the light of primary research”) outlines a shared tourism vision for the 13 settlements of Tiszazug. The diagnosis: the region is a “sleeping giant” – 92–94% of the district's guest nights go to a single attraction (the Cserkeszőlő thermal bath), while 80% of the 166 tourism attractions have an unmanaged Google profile. It builds on a triple methodology: classic data analysis (KSH, NTAK), engagement-based research (in-depth interviews with mayors and providers, resident and visitor surveys) and a technology-based, AI-assisted digital visibility audit. It adapts lessons from four international models (Saba, Plan T / Austria, Linz DMO 4.0, Perth) and outlines the Tiszazug 2035 vision around four pillars (a regional “Visit Tiszazug” brand, networked operation / DMO, digital visibility, experience-based tourism), plus stakeholder-engagement tools (including a strategy-generator website). Other speakers: Gusztav Laving, Adam Bauer, Anita Galo and Zsolt Kabaly.",
    "type": "talk",
    "typeLabel": "Talk",
    "date": "2026-04-29",
    "year": "2026",
    "location": "Baghy-Szinyei Merse Manor, Cserkeszőlő, Hungary",
    "organizer": "“Tourism opportunities of businesses in local economic development” – organizer: “Crown and Sword” Rural and Regional Development Foundation (Business Environment Development Program)",
    "tags": [
      "tourism strategy",
      "destination development",
      "Tiszazug"
    ],
    "audience": "municipalities, mayors, tourism entrepreneurs, destination management",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“The region is a sleeping giant: 92–94% of the district's guest nights go to a single attraction, while the value of the other 12 settlements stays invisible.” 80% of the 166 tourism attractions have an unmanaged Google profile.",
    "cover": "/images/manual-covers/tiszazug.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "Tiszazug 2035 – regional tourism strategy | Adam Schmutz",
    "seoDescription": "Adam Schmutz on repositioning the tourism of the Tiszazug region: primary research, 4 international models and the Visit Tiszazug vision for 2035.",
    "featured": true,
    "order": 10,
    "size": "sm"
  },
  {
    "id": "6",
    "slug": "digitalization-sustainability-earth-day-conference-balaton-2026",
    "title": "Digitalisation and sustainability: Earth Day",
    "summary": "Sustainability can only be measured digitally – and from 27 September 2026 the EU ECGT regulation requires measured evidence for “green” claims. The talk, at the Smart Tour project's Earth Day opening event, showed how digitalization reduces Lake Balaton's environmental footprint.",
    "description": "Adam Schmutz's talk at the “Earth Day Conference in the Lake Balaton Region”, the opening event of the international Smart Tour project (Interreg Europe), organized by the Lake Balaton Integration Public Benefit Nonprofit Ltd. The central thesis: digitalization and sustainability are two sides of the same work – sustainability can only be measured, communicated and optimized digitally, and digitalization is meaningful only if its business or environmental impact is measurable. It builds on fresh data (e.g. 93% of global travelers would travel more sustainably; 62.4% of bookings happen online; Hungarian SMEs' digital intensity is 57.4% vs. the EU average of 72.9%) and presents practical SME-level tools in three roles: TOOL (sensor, dashboard, automation – e.g. Shelly, tado°, Sensgreen), CHANNEL (booking email, push, nudge) and SOLUTION (custom GPT and predictive decision support). Special emphasis is on the EU “Empowering Consumers for the Green Transition” (ECGT, 2024/825) regulation: from 27 September 2026, “green” claims require measured evidence – a regulatory and financial, not a moral, question. Hungarian and international good practices (Kerca Biofarm, Boutiquehotel Stadthalle, Adrère Amellal, Eccleston Square Hotel) close the talk. Other speakers included Dr. Gabor Molnar, Balazs Kovacs (Good Deal Consulting, Vienna – EU Climate Pact ambassador), Dr. Zsuzsanna Varadi (Visit Hungary) and Dr. Terez Horvath (VisitBalaton365).",
    "type": "talk",
    "typeLabel": "Talk",
    "date": "2026-04-28",
    "year": "2026",
    "location": "Lake Balaton region, Hungary (Earth Day Conference – Smart Tour opening event)",
    "organizer": "Earth Day Conference in the Lake Balaton Region – opening event of the Smart Tour project (Interreg Europe); organizer: Lake Balaton Integration Public Benefit Nonprofit Ltd.",
    "tags": [
      "sustainable tourism",
      "digitalization",
      "sustainability"
    ],
    "audience": "accommodation providers, guesthouses, tourism SMEs, destination management",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“Don't talk to the guest about sustainability — talk about numbers on sustainability.” From 27 September 2026 the EU ECGT requires measured evidence for “green” claims: evidence = data, data = digitalization.",
    "cover": "/images/references/foldnap-2026/schmutz-adam-eloadas-foldnapi-konferencia-balaton-2026-01.jpg",
    "photos": [
      "/images/references/foldnap-2026/schmutz-adam-eloadas-foldnapi-konferencia-balaton-2026-01.jpg",
      "/images/references/foldnap-2026/schmutz-adam-eloadas-foldnapi-konferencia-balaton-2026-02.jpg",
      "/images/references/foldnap-2026/foldnapi-konferencia-balaton-2026-kozonseg.jpg"
    ],
    "imageAlt": "Adam Schmutz speaking at the Earth Day Conference with the “Digitalization ↔ Sustainability” slide (Lake Balaton, 2026) | Adam Schmutz presenting data on sustainability and digitalization trends at the Earth Day Conference | The Earth Day Conference audience during the talk (Smart Tour opening event, Lake Balaton, 2026)",
    "seoTitle": "Digitalization and sustainability in tourism – talk | Adam Schmutz",
    "seoDescription": "Adam Schmutz at the Earth Day Conference: how digitalization reduces environmental footprint, and what the EU ECGT requires from Lake Balaton accommodations from 2026.",
    "featured": true,
    "order": 9,
    "size": "wide"
  },
  {
    "id": "1",
    "slug": "ai-based-solutions-tourism-digiturismo-podcast",
    "title": "AI solutions in tourism on DigiTurismo",
    "summary": "How did artificial intelligence become the “invisible infrastructure” of tourism – and why is GEO, not SEO, the key in the age of AI engines? A returning guest on the second AI episode of the DigiTurismo podcast, as one of Hungary's reference points on the topic.",
    "description": "Adam Schmutz was a guest for the second time on the DigiTurismo podcast to continue an inexhaustible topic: the role of artificial intelligence in tourism. The conversation explores how AI has become a kind of “invisible infrastructure” sitting behind Google Maps searches and personalized offers. It covers why GEO (Generative Engine Optimization – not SEO!) matters in the age of AI engines, and why AI will never fully replace human hospitality. The DigiTurismo hosts are Peter Princzinger, managing director of VisitBalaton365, and Andras Mihalovits. The episode was also covered by turizmus.com (28 April 2026).",
    "type": "podcast",
    "typeLabel": "Podcast",
    "date": "2026-04-23",
    "year": "2026",
    "location": "Online (DigiTurismo podcast)",
    "organizer": "DigiTurismo (YouTube channel)",
    "tags": [
      "artificial intelligence",
      "tourism",
      "GEO"
    ],
    "audience": "tourism and hospitality professionals, SMEs",
    "language": "HU",
    "videoUrl": "https://www.youtube.com/embed/T0_pSTHVTqI",
    "pressUrl": "https://turizmus.com/cikk/podcast/mesterseges-intelligencia-turizmus-schmutz-adam-novitatis",
    "quote": "“Artificial intelligence will never fully replace human hospitality – but those who don't understand GEO today will fall behind in the age of AI engines.”",
    "cover": "/images/references/digiturismo-ai-2026/digiturismo-ai-podcast-schmutz-adam-studio-01.jpg",
    "photos": [
      "/images/references/digiturismo-ai-2026/digiturismo-ai-podcast-schmutz-adam-studio-01.jpg",
      "/images/references/digiturismo-ai-2026/digiturismo-ai-podcast-schmutz-adam-02.jpg",
      "/images/references/digiturismo-ai-2026/digiturismo-ai-podcast-schmutz-adam-csapatkep-03.jpg"
    ],
    "imageAlt": "Adam Schmutz during the recording of the DigiTurismo podcast AI episode in the TREND FM studio | Adam Schmutz talking about the role of AI in tourism on the DigiTurismo podcast | Adam Schmutz with the DigiTurismo podcast hosts in the TREND FM studio",
    "seoTitle": "AI in tourism and GEO | Adam Schmutz – DigiTurismo podcast",
    "seoDescription": "How AI became the invisible infrastructure of tourism, and why GEO is the key in the age of AI engines – Adam Schmutz on the DigiTurismo podcast.",
    "featured": true,
    "order": 4,
    "size": "sm"
  },
  {
    "id": "3",
    "slug": "innovation-opportunities-tourism-panel-kultkikoto",
    "title": "Innovation in tourism (KULTKIKÖTŐ panel)",
    "summary": "A panel discussion on tourism innovation at the KULTKIKÖTŐ cultural tourism conference, together with an expert from Visit Hungary. Topics: AI “becoming invisible”, GEO, and the findings of an own study of 73 Lake Balaton businesses.",
    "description": "Adam Schmutz discussed the innovation opportunities of tourism on the panel of the KULTKIKÖTŐ – “In the Same Boat” cultural tourism conference. His fellow panelist was Botond Boros, head of the business intelligence and digital solutions division at Visit Hungary; the panel was moderated by Daniel Molnar (National Innovation Agency). A central idea: AI has “become invisible” – no longer a standalone tool but part of the infrastructure of search engines, maps and booking systems, which is why GEO (Generative Engine Optimization) matters more and more. The panel built on own research: of 73 Lake Balaton gastro-tourism businesses, 92% have an advanced digital presence yet only 5.5% sell online (a 17:1 ratio) – the barrier to innovation is not a lack of technology but decision logic. It also covered front-end vs. back-end AI, a case study (direct booking rising from 23% to 41% in a year), and the idea that in tourism the best innovation is invisible and the technology-to-human “translation” is the key.",
    "type": "panel",
    "typeLabel": "Panel",
    "date": "2026-03-26",
    "year": "2026",
    "location": "Balatonföldvár, Hungary (KULTKIKÖTŐ – In the Same Boat conference)",
    "organizer": "KULTKIKÖTŐ – In the Same Boat Cultural Tourism Conference (2026)",
    "tags": [
      "tourism innovation",
      "artificial intelligence",
      "GEO"
    ],
    "audience": "tourism professionals, hotel managers, destination management, SMEs",
    "language": "HU",
    "videoUrl": "https://open.spotify.com/embed/episode/7CdVcgHphJMnxG6opyonRf",
    "pressUrl": "https://kultkikoto.hu/hirek/kultkikoto-konferencia-sajtohir/",
    "quote": "“The barrier to innovation in tourism is not a lack of technology, but decision logic.” (73 Lake Balaton businesses: 92% advanced digital presence, but only 5.5% selling online – a 17:1 ratio.)",
    "cover": "/images/references/kultkikoto-2026/schmutz-adam-podiumbeszelgetes-kultkikoto-2026-01.jpg",
    "photos": [
      "/images/references/kultkikoto-2026/schmutz-adam-podiumbeszelgetes-kultkikoto-2026-01.jpg",
      "/images/references/kultkikoto-2026/schmutz-adam-podiumbeszelgetes-kultkikoto-2026-02.jpg",
      "/images/references/kultkikoto-2026/schmutz-adam-boros-botond-podiumbeszelgetes-kultkikoto-2026-03.jpg",
      "/images/references/kultkikoto-2026/boros-botond-visit-hungary-podiumbeszelgetes-kultkikoto-2026-04.jpg",
      "/images/references/kultkikoto-2026/kultkikoto-2026-konferencia-kozonseg-01.jpg",
      "/images/references/kultkikoto-2026/kultkikoto-2026-konferencia-kozonseg-kerdes-02.jpg",
      "/images/references/kultkikoto-2026/kultkikoto-2026-konferencia-kartyak.jpg"
    ],
    "imageAlt": "Adam Schmutz on the panel of the KULTKIKÖTŐ conference (Balatonföldvár, 2026) | Adam Schmutz gesturing while speaking on the KULTKIKÖTŐ conference panel | Adam Schmutz and Botond Boros (Visit Hungary) discussing tourism innovation at the KULTKIKÖTŐ conference | Botond Boros, Visit Hungary expert, on the panel at the KULTKIKÖTŐ conference | The audience of the KULTKIKÖTŐ conference during the panel | A question from the audience at the KULTKIKÖTŐ conference panel | KULTKIKÖTŐ – In the Same Boat Cultural Tourism Conference 2026 – conference badges",
    "seoTitle": "Innovation in tourism – panel discussion | Adam Schmutz",
    "seoDescription": "Adam Schmutz on tourism innovation: invisible AI, GEO and a study of 73 Lake Balaton businesses at the KULTKIKÖTŐ conference.",
    "featured": true,
    "order": 14,
    "size": "sm"
  },
  {
    "id": "12",
    "slug": "competitive-tourism-digitalization-panel-balaton365",
    "title": "Competitive tourism: everyday digitalisation",
    "summary": "Moderating the Balaton365 workshop panel “Competitive tourism – digitalization in everyday practice” (Balatonkenese), with prominent industry figures (MTPA, VIMOSZ, MTA, CheckINN, VisitBalaton365) – on the digital competitiveness of the destination.",
    "description": "Adam Schmutz moderated the two-hour closing panel discussion of the Balaton365 workshop, titled “Competitive tourism – digitalization in everyday practice”, in Balatonkenese. The discussion explored the competitiveness of tourism and the practical application of digitalization, with several leading figures of the Hungarian tourism industry. Panelists: Natalia Oszko-Jakab (MTPA), Dr. Zsofia Liziczayne Kovacs (MTMT), Lajos Borocz (VIMOSZ), Krisztina Bacsi (MTA), Petra Gedei (CheckINN), Dr. Terez Horvath (VisitBalaton365) and Daniel Damosy (Nitro Communications). The Balaton365 workshop program also covered the region's tourism results and plans, the performance of Hungarian tourism (MTÜ, Visit Hungary) and the DIMOP Plus developments.",
    "type": "panel",
    "typeLabel": "Panel",
    "date": "2026-03-12",
    "year": "2026",
    "location": "Balatonkenese, Hungary (Balaton365 workshop)",
    "organizer": "Balaton365 workshop – VisitBalaton365 (DMO), Balatonkenese, 12 March 2026",
    "tags": [
      "competitive tourism",
      "digitalization",
      "panel discussion"
    ],
    "audience": "tourism professionals, providers, destination management, decision-makers",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "The “Competitive tourism – digitalization in everyday practice” panel explored how Hungarian tourism can be made more competitive through the everyday, practical application of digitalization.",
    "cover": "/images/references/balaton365-balatonkenese-2026/schmutz-adam-moderator-balaton365-balatonkenese-2026-01.jpg",
    "photos": [
      "/images/references/balaton365-balatonkenese-2026/schmutz-adam-moderator-balaton365-balatonkenese-2026-01.jpg",
      "/images/references/balaton365-balatonkenese-2026/balaton365-podiumbeszelgetes-panel-02.jpg",
      "/images/references/balaton365-balatonkenese-2026/balaton365-podiumbeszelgetes-panelistak-03.jpg",
      "/images/references/balaton365-balatonkenese-2026/balaton365-podiumbeszelgetes-panelistak-04.jpg"
    ],
    "imageAlt": "Adam Schmutz moderating the “Competitive tourism – digitalization in everyday practice” panel at the Balaton365 workshop (Balatonkenese, 2026) | The panelists of the discussion at the Balaton365 workshop | A speaker at the Balaton365 workshop panel (Balatonkenese, 2026) | The panelists at the Balaton365 workshop",
    "seoTitle": "Competitive tourism and digitalization – panel discussion | Adam Schmutz",
    "seoDescription": "Adam Schmutz moderated the Balaton365 workshop panel on tourism competitiveness and the everyday application of digitalization (Balatonkenese, 2026).",
    "featured": true,
    "order": 15,
    "size": "lg"
  },
  {
    "id": "10",
    "slug": "ai4tourism-itb-berlin-2026-exhibitor",
    "title": "ITB Berlin 2026 with AI4Tourism",
    "summary": "At the world's largest tourism trade fair, ITB Berlin, we launched the AI4tourism brand (March 2026). Over 250 professional contacts in three days – our goal is to be the clear, trustworthy voice in the noise around AI: through education, a use-case bank and a consulting marketplace.",
    "description": "ITB Berlin – the world's largest tourism trade fair – was the venue for the official launch of the AI4tourism brand (Hall 6.1, Stand 248). Over three days we collected more than 250 contacts from independent hotels, tour operators, DMOs, OTAs and technology platforms from more than 30 countries – and the concept drew huge interest. AI4tourism's mission is to be the clear, trustworthy voice in the noise around AI for the tourism sector. The market is full of AI tools; what's missing is clarity about what actually pays off – and what doesn't. The brand has three pillars: (1) EDUCATION – understandable, practical knowledge about the real possibilities of AI; (2) USE-CASE BANK – concrete, proven use cases from which players can choose a solution fitting their size and situation; (3) CONSULTING/DEVELOPMENT MARKETPLACE – where businesses meet the right experts and developers for implementation. The ITB experience confirmed the starting point: everyone watches AI, but few are sure they're looking at the right thing – exactly the gap AI4tourism aims to close.",
    "type": "exhibition",
    "typeLabel": "Exhibition",
    "date": "2026-03-03 – 2026-03-05",
    "year": "2026",
    "location": "Berlin, Germany (ITB Berlin, Messe Berlin – Hall 6.1, Stand 248)",
    "organizer": "ITB Berlin 2026 – the world's largest tourism trade fair (Messe Berlin), 60th anniversary edition, 3–5 March 2026",
    "tags": [
      "ITB Berlin",
      "AI4tourism",
      "AI in tourism"
    ],
    "audience": "independent hotels, hotel managers (40–120 rooms), DMOs, OTAs, technology partners",
    "language": "EN",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“Most tourism SMEs aren't short on AI tools. They're short on clarity.” AI4tourism shows where AI delivers measurable revenue growth or cost reduction – before an accommodation spends its budget.",
    "cover": "/images/references/itb-berlin-2026/ai4tourism-stand-itb-berlin-2026-01.jpg",
    "photos": [
      "/images/references/itb-berlin-2026/ai4tourism-stand-itb-berlin-2026-01.jpg",
      "/images/references/itb-berlin-2026/ai4tourism-itb-berlin-2026-standbeszelgetes-02.jpg",
      "/images/references/itb-berlin-2026/ai4tourism-itb-berlin-2026-hall61-stand-03.jpg",
      "/images/references/itb-berlin-2026/ai4tourism-itb-berlin-2026-latogatok-04.jpg",
      "/images/references/itb-berlin-2026/ai4tourism-itb-berlin-2026-bemutato-05.jpg"
    ],
    "imageAlt": "The AI4tourism stand at ITB Berlin 2026 (Hall 6.1, Stand 248) – “From AI confusion to clear action” | Conversation at the AI4tourism stand at ITB Berlin 2026 | The AI4tourism stand in Hall 6.1 of ITB Berlin, with visitors | Visitors at the AI4tourism stand at ITB Berlin 2026 | Presenting the AI4tourism solution at the ITB Berlin 2026 stand",
    "seoTitle": "AI4tourism at ITB Berlin 2026 | international exhibitor participation",
    "seoDescription": "The AI4tourism brand at ITB Berlin 2026 (Hall 6.1, Stand 248): where does AI deliver measurable returns for an independent hotel? 250+ conversations, 30+ countries.",
    "featured": true,
    "order": 8,
    "size": "sm"
  },
  {
    "id": "2",
    "slug": "tech-optimism-digital-maturity-digiturismo-podcast",
    "title": "Tech-optimism and digital maturity",
    "summary": "Does an SME still need a website in 2026? What does it mean to be a tech-optimist, and how can digital maturity be measured? A conversation on the DigiTurismo podcast about the practical questions of digital tourism.",
    "description": "A conversation with Adam Schmutz, digital tourism expert, about what it means to be a tech-optimist and how a company's digital maturity can be measured. It covers whether a website is still needed in 2026, what Google My Business is, and why it pays off for an SME to develop its digital presence. The discussion also touches on the three things an SME must focus on to be successful in the future.",
    "type": "podcast",
    "typeLabel": "Podcast",
    "date": "2026-01-29",
    "year": "2026",
    "location": "Online (DigiTurismo podcast)",
    "organizer": "DigiTurismo (YouTube channel)",
    "tags": [
      "tech-optimism",
      "digital maturity",
      "SME"
    ],
    "audience": "tourism SMEs, entrepreneurs",
    "language": "HU",
    "videoUrl": "https://www.youtube.com/embed/ezVeO0iiscU",
    "pressUrl": "https://youtu.be/ezVeO0iiscU",
    "quote": "Q: Does an SME still need a website in 2026? A: Yes – but without Google My Business and digital maturity, a website alone is not enough for success.",
    "cover": "/images/references/digiturismo-techoptimizmus-2026/digiturismo-techoptimizmus-podcast-csapatkep-01.jpg",
    "photos": [
      "/images/references/digiturismo-techoptimizmus-2026/digiturismo-techoptimizmus-podcast-csapatkep-01.jpg",
      "/images/references/digiturismo-techoptimizmus-2026/digiturismo-techoptimizmus-podcast-schmutz-adam-02.jpg",
      "/images/references/digiturismo-techoptimizmus-2026/digiturismo-techoptimizmus-podcast-studio-03.jpg",
      "/images/references/digiturismo-techoptimizmus-2026/digiturismo-techoptimizmus-podcast-beszelgetes-04.jpg"
    ],
    "imageAlt": "Adam Schmutz with the DigiTurismo podcast hosts during the tech-optimism episode | Adam Schmutz talking about digital maturity on the DigiTurismo podcast | Adam Schmutz during the DigiTurismo podcast recording in the TREND FM studio | Relaxed conversation during the recording of the DigiTurismo tech-optimism episode",
    "seoTitle": "Tech-optimism and digital maturity | Adam Schmutz – DigiTurismo",
    "seoDescription": "What tech-optimism means, how digital maturity is measured, and whether a website is needed in 2026 – Adam Schmutz on the digitalization of tourism SMEs.",
    "featured": false,
    "order": 17,
    "size": "sm"
  },
  {
    "id": "4",
    "slug": "lake-balaton-gastro-tourism-online-sales-turizmus-bulletin-2025",
    "title": "Why Balaton gastro firms don't sell online",
    "summary": "Peer-reviewed academic study in Turizmus Bulletin (Corvinus University of Budapest): the digital maturity and online sales propensity of 73 Lake Balaton gastro-tourism businesses. The surprising result – 92% have an advanced digital presence, but only 5.5% sell online (a 17:1 ratio) – is the research foundation of our entire online-sales practice.",
    "description": "Adam Schmutz's (PhD student, University of Pannonia) peer-reviewed study was published in Turizmus Bulletin Vol. XXV, Issue 4 (2025), DOI: 10.14267/TURBULL.2025v25n4.3. It examines the digital behavior of 73 Lake Balaton gastro-tourism micro-enterprises using a three-step mixed-method approach: automated data collection (Google Maps), structured website analysis, and analysis of real sales interactions via a startup sales team – revealing undistorted, spontaneous entrepreneurial reactions. The main finding is the “capability–adoption gap”: 92% have an advanced digital presence, yet only 5.5% use full-scale online sales (a 17:1 ratio). Versus the Western-European ~30% and Hungarian urban 23% averages, the Lake Balaton 5.5% points to a rural structural phenomenon. The study uses the TOE (Technology–Organization–Environment) framework and identifies five rejection patterns (seasonality, primacy of the personal touch, operational flexibility, alternative revenue models, general digital scepticism). Key takeaway: the barrier to digital adoption is not a lack of competence but context-bound decision logic – businesses deliberately separate marketing and sales (“digital front, analog back”). Also covered by turizmus.com (Mark Miskolczi, 5 February 2026).",
    "type": "publication",
    "typeLabel": "Publication",
    "date": "2025",
    "year": "2025",
    "location": "Turizmus Bulletin / Corvinus University of Budapest (online, open access)",
    "organizer": "Turizmus Bulletin, Vol. XXV, Issue 4 (2025) – DOI: 10.14267/TURBULL.2025v25n4.3",
    "tags": [
      "gastro-tourism",
      "technology adoption",
      "online sales"
    ],
    "audience": "researchers, decision-makers, destination managers, technology providers, tourism SMEs",
    "language": "HU (with English abstract)",
    "videoUrl": "",
    "pressUrl": "https://journals.lib.uni-corvinus.hu/index.php/turizmusbulletin/article/view/2324, https://turizmus.com/cikk/business-travel/corvinus-egyetem-turizmus-bulletin-online-ter-balaton-gasztroturizmus",
    "quote": "“Of 73 Lake Balaton gastro-tourism businesses, 92% have an advanced digital presence yet only 5.5% sell online (a 17:1 ratio) – the barrier to digital adoption is not a lack of competence, but decision logic.”",
    "cover": "/images/manual-covers/turizmus-bulletin-2025.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "Lake Balaton gastro-tourism and online sales – academic study | Adam Schmutz",
    "seoDescription": "Adam Schmutz's Turizmus Bulletin study: digital maturity and online sales of 73 Lake Balaton gastro businesses – the 92% vs. 5.5% paradox.",
    "featured": true,
    "order": 1,
    "size": "wide"
  },
  {
    "id": "11",
    "slug": "ai-training-visitbalaton365-dmo",
    "title": "AI training for VisitBalaton365",
    "summary": "A full-day, hands-on AI training for the VisitBalaton365 DMO team – from AI basics through prompting and data processing to image generation and the “Google Maps for DMOs” module. Delivered by the three-person team (Adam Schmutz, Bence Bukovec, Eszter Schmutz), with real Lake Balaton examples and international DMO best practices.",
    "description": "A full-day, practice-oriented AI training for the staff of the VisitBalaton365 DMO, delivered by the team (Adam Schmutz, Bence Bukovec and Eszter Schmutz). Four modules: (1) AI basics and prompting – what AI is, how generative AI works, “AI as a mirror”, hallucination, and the 5 elements of an effective prompt (role, goal, audience, style, format); (2) copywriting and content planning with AI tools – tourism content types, prompt templates, multichannel content and AI detection; (3) data processing and note-taking (NotebookLM, Gemini) – quickly summarizing reports and statistics; (4) image generation and visual content (Canva AI, Firefly, Leonardo, Sora), plus “Google Maps for DMOs”. Based on a pre-survey (66.7% basic AI users; 83.3% would use it for copywriting; most popular tool: ChatGPT). It featured hands-on tasks with real Lake Balaton examples and a showcase of international DMO best practices (Visit Finland, Visit Norway “Aurora”, Helsinki “Lokki”, the Italian @venereitalia23 AI influencer, NAVITIME Japan). It also covered the four phases of DMO-level AI maturity (Beginners → Early adopters → AI pioneers) and ethical/data-protection (GDPR) aspects.",
    "type": "workshop",
    "typeLabel": "Workshop",
    "date": "2025-10-17",
    "year": "2025",
    "location": "Keszthely, Hungary (VisitBalaton365 DMO office)",
    "organizer": "Internal AI training for the VisitBalaton365 (DMO) team; delivered by: Adam Schmutz, Bence Bukovec and Eszter Schmutz",
    "tags": [
      "AI training",
      "DMO",
      "prompting"
    ],
    "audience": "destination management organization (DMO) staff, tourism professionals",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“AI is a tool, not a magic wand – a good question is the key to a good answer.” DMO staff received practical, Hungarian-market-tailored AI tools: copywriting, research, data processing and image generation.",
    "cover": "/images/references/ai-kepzes-visitbalaton365-dmo-2025/schmutz-adam-ai-kepzes-visitbalaton365-dmo-keszthely-2025-01.jpg",
    "photos": [
      "/images/references/ai-kepzes-visitbalaton365-dmo-2025/schmutz-adam-ai-kepzes-visitbalaton365-dmo-keszthely-2025-01.jpg",
      "/images/references/ai-kepzes-visitbalaton365-dmo-2025/schmutz-adam-ai-kepzes-visitbalaton365-dmo-keszthely-2025-02.jpg",
      "/images/references/ai-kepzes-visitbalaton365-dmo-2025/schmutz-adam-ai-kepzes-visitbalaton365-dmo-keszthely-2025-03.jpg",
      "/images/references/ai-kepzes-visitbalaton365-dmo-2025/schmutz-adam-ai-kepzes-visitbalaton365-dmo-keszthely-2025-04.jpg",
      "/images/references/ai-kepzes-visitbalaton365-dmo-2025/schmutz-adam-ai-kepzes-visitbalaton365-dmo-keszthely-2025-05.jpg"
    ],
    "imageAlt": "01: AI training in the VisitBalaton365 training room in Keszthely; participants working on laptops, the AI slide on the screen, the map of Lake Balaton on the wall. 02: VisitBalaton365 DMO staff at the U-shaped tables during the AI training, in front of the Lake Balaton map wall. 03: Participants practicing AI tools on laptops during the training. 04: The full group of the training room at work. 05: DMO staff attentively following the AI training demo.",
    "seoTitle": "AI training for the VisitBalaton365 DMO | Adam Schmutz",
    "seoDescription": "A full-day, hands-on AI training for the VisitBalaton365 DMO team: prompting, AI copywriting, data processing, image generation and “Google Maps for DMOs”.",
    "featured": true,
    "order": 13,
    "size": "sm"
  },
  {
    "id": "13",
    "slug": "visible-tourism-tourism-summit-2025-exhibitor",
    "title": "Tourism Summit 2025 with Visible Tourism",
    "summary": "As an exhibitor at Tourism Summit 2025 (Bálna, Budapest) with the Visible Tourism brand, which boosts the online visibility of tourism SMEs and destinations: Google Business Profile mentoring, GEO/AEO and visibility audits on Google Maps and in AI search.",
    "description": "We exhibited at Tourism Summit 2025 (organizer: Visit Hungary; venue: Bálna, Budapest) with the Visible Tourism brand – motto: “Tourists Ask Google. We Help You Answer.” / “Stay visible, stay relevant, stay on the map.” Visible Tourism helps destinations and tourism businesses be present – accurately and findably – exactly where visitors actually decide: on Google Maps, in Street View and in AI-driven search. Services: online visibility growth and a Google Business Profile (GBP) mentoring program plus GEO/AEO for tourism SMEs; visibility audits on Google Maps and AI search engines for destinations and DMOs, improving POIs, routes, opening hours and business data, publishing 360° Street View, and actually editing Google Maps content. The approach doesn't build a campaign but “infrastructure” within the Google ecosystem, with measurable before-and-after results that DMOs can also present to their partners. Visible Tourism is our own brand.",
    "type": "exhibition",
    "typeLabel": "Exhibition",
    "date": "2025-10-14 – 2025-10-15",
    "year": "2025",
    "location": "Bálna, Budapest, Hungary (Tourism Summit 2025)",
    "organizer": "Tourism Summit 2025 – organizer: Visit Hungary; venue: Bálna Budapest, 14–15 October 2025",
    "tags": [
      "Visible Tourism",
      "Google Business Profile",
      "GEO"
    ],
    "audience": "destinations and DMOs, tourism SMEs, accommodations, attractions",
    "language": "HU / EN",
    "videoUrl": "",
    "pressUrl": "https://www.visibletourism.com/",
    "quote": "“Tourists Ask Google. We Help You Answer.” Visible Tourism boosts the visibility of tourism SMEs and destinations on Google Maps and in AI search – because if you're missing from the results, you're missing from the traveler's journey.",
    "cover": "/images/references/tourism-summit-2025/visible-tourism-stand-tourism-summit-2025-01.jpg",
    "photos": [
      "/images/references/tourism-summit-2025/visible-tourism-stand-tourism-summit-2025-01.jpg",
      "/images/references/tourism-summit-2025/visible-tourism-tourism-summit-2025-csapat-02.jpg",
      "/images/references/tourism-summit-2025/visible-tourism-tourism-summit-2025-csapat-03.jpg",
      "/images/references/tourism-summit-2025/visible-tourism-tourism-summit-2025-stand-munka-04.jpg",
      "/images/references/tourism-summit-2025/schmutz-adam-visible-tourism-tourism-summit-2025-05.jpg"
    ],
    "imageAlt": "The Visible Tourism stand at Tourism Summit 2025 (Bálna, Budapest) – “Stay visible, stay relevant, stay on the map.” | The Visible Tourism team at the stand at Tourism Summit 2025 | The Visible Tourism team at the Tourism Summit 2025 stand | A professional conversation at the Visible Tourism stand at Tourism Summit 2025 | Adam Schmutz talking with a visitor at the Visible Tourism stand at Tourism Summit 2025",
    "seoTitle": "Visible Tourism at Tourism Summit 2025 | Google Maps & AI visibility",
    "seoDescription": "The Visible Tourism brand at Tourism Summit 2025 (Bálna, Budapest): Google Business Profile mentoring, GEO/AEO and destination visibility audits on Google Maps and AI search.",
    "featured": true,
    "order": 16,
    "size": "sm"
  },
  {
    "id": "14",
    "slug": "ai-opener-visitbalaton365-ai-journey",
    "title": "AI Opener: VisitBalaton365's AI journey",
    "summary": "On an international stage, in English: VisitBalaton365 DMO's practical AI journey at the AI Opener Bootcamp in Edinburgh, to inspire other European destination management organizations (Edinburgh Futures Institute, University of Edinburgh).",
    "description": "Adam Schmutz's (VisitBalaton365) English-language talk at the AI Opener Bootcamp, aimed at sharing VisitBalaton365 DMO's practical AI experience with other destination management organizations. Context: the Lake Balaton destination spans 180 settlements, 3.2 million visitors and more than 9 million guest nights (2024). The talk was built on two main pillars. (1) Preparing the teams (AI education and internal integration): monthly AI sessions, SOPs co-created with AI, an internal AI toolkit, a prompt library, and a “role evolution” framework for the optimal distribution of human and AI tasks. (2) Enriching the digital presence (data for AI search engines and visitors) – in partnership with Visible Tourism: mapping Lake Balaton's uncharted hiking and cycling routes, 360° Street View content for the main attractions, sorting out admin access to Google Business Profiles, and turning static listings into a dynamic marketing tool. The message: DMOs can make their destination visible to both AI search engines and visitors through hands-on internal capability-building and concrete work within the Google ecosystem.",
    "type": "talk",
    "typeLabel": "Talk",
    "date": "2025-09-23 – 2025-09-24",
    "year": "2025",
    "location": "Edinburgh Futures Institute, The University of Edinburgh, Edinburgh, United Kingdom",
    "organizer": "AI Opener Bootcamp (23–24 September 2025)",
    "tags": [
      "AI",
      "DMO",
      "VisitBalaton365"
    ],
    "audience": "destination management organizations (DMOs), tourism decision-makers",
    "language": "EN",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“Sharing practical experiences and ongoing initiatives to inspire fellow Destination Marketing Organizations.” VisitBalaton365 makes the destination visible to AI search engines and visitors through internal AI capability-building and concrete work in the Google ecosystem.",
    "cover": "/images/manual-covers/ai-opener.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "AI Opener – VisitBalaton365's AI journey | Adam Schmutz",
    "seoDescription": "Adam Schmutz's talk at the AI Opener Bootcamp: how VisitBalaton365 DMO builds AI into its teams and digital visibility – to inspire other DMOs.",
    "featured": true,
    "order": 7,
    "size": "lg"
  },
  {
    "id": "15",
    "slug": "digital-revolution-in-tourism-talk",
    "title": "Digital revolution in tourism",
    "summary": "A comprehensive overview of the digital transformation of tourism: from online visibility and the Google ecosystem (Google Business Profile, zero-click search) to AI assistants – throughout backed by own Lake Balaton research data (Hévíz, 2025).",
    "description": "Adam Schmutz's (digital tourism expert, PhD student) comprehensive professional talk on the digital transformation of tourism. Five main topics: (1) the role of digitalization and changing guest expectations (79% of guests book online, 76% plan their trip on mobile); (2) online presence (paid–owned–earned) and the digitalization of the customer journey; (3) Google as the key to future online visibility – zero-click search and Google Maps as a decision-making platform; (4) the role of destination management organizations (DMOs) and Google Business Profile optimization; (5) online sales (AIDA) and AI assistants/chatbots in the guest cycle. The talk is backed by own, peer-reviewed Lake Balaton research data, including the gastro-tourism “capability–adoption” paradox (92% digital presence vs. 5.5% online sales).",
    "type": "talk",
    "typeLabel": "Talk",
    "date": "2025-07-18",
    "year": "2025",
    "location": "Hévíz, Hungary",
    "organizer": "HÉVÍZ Tourism Association (organizer), Hévíz. Speaker: Adam Schmutz. DIGITALIZE (Interreg Europe) project context.",
    "tags": [
      "digital transformation",
      "online visibility",
      "Google Business Profile"
    ],
    "audience": "tourism providers, accommodations, SMEs, municipalities, DMOs, destination developers",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“If you're not visible in the Google ecosystem, you're practically invisible online” – 94% of searches happen on Google platforms, and nearly half are zero-click. | In Lake Balaton gastro-tourism, 92% have a digital presence but only 5.5% sell online – a 17:1 ratio that is unique even internationally.",
    "cover": "/images/references/digitalis-forradalom-turizmus-heviz-2025/schmutz-adam-digitalis-forradalom-turizmus-heviz-2025-01.jpg",
    "photos": [
      "/images/references/digitalis-forradalom-turizmus-heviz-2025/schmutz-adam-digitalis-forradalom-turizmus-heviz-2025-01.jpg",
      "/images/references/digitalis-forradalom-turizmus-heviz-2025/schmutz-adam-digitalis-forradalom-turizmus-heviz-2025-02.jpg",
      "/images/references/digitalis-forradalom-turizmus-heviz-2025/schmutz-adam-digitalis-forradalom-turizmus-heviz-2025-03.jpg",
      "/images/references/digitalis-forradalom-turizmus-heviz-2025/schmutz-adam-digitalis-forradalom-turizmus-heviz-2025-04.jpg",
      "/images/references/digitalis-forradalom-turizmus-heviz-2025/schmutz-adam-digitalis-forradalom-turizmus-heviz-2025-05.jpg",
      "/images/references/digitalis-forradalom-turizmus-heviz-2025/schmutz-adam-digitalis-forradalom-turizmus-heviz-2025-06.jpg"
    ],
    "imageAlt": "01: The “Digital revolution in tourism” title slide on the screen on the event stage (Hévíz, 2025). 02–06: Adam Schmutz speaking about the digitalization of tourism, next to the DIGITALIZE (Interreg Europe) project banner.",
    "seoTitle": "Digital revolution in tourism – talk | Adam Schmutz",
    "seoDescription": "Adam Schmutz's talk on the digital transformation of tourism: online visibility, Google Business Profile, zero-click search and AI – with real Lake Balaton research data.",
    "featured": false,
    "order": 5,
    "size": "sm"
  },
  {
    "id": "17",
    "slug": "package-offer-product-development-workshop-keszthely-visitbalaton365-2025",
    "title": "Package and product development workshop",
    "summary": "A two-day product development workshop with 20 Lake Balaton providers (VisitBalaton365, Keszthely): Adam Schmutz, as facilitator, guided the small-group work with a planning canvas template. The result didn't stay a plan – a real, bookable experience package was born (“Lake Balaton like you've never seen it!”), also covered by Turizmus.com.",
    "description": "A two-day, practice-oriented package offer and product development workshop at VisitBalaton365's brand-new destination management training center in Keszthely, with 20 Lake Balaton tourism providers. The program ran from the concept and legal aspects of package offers through cycling packages to pricing, positioning, promotion and invoicing. As the workshop's facilitator, Adam Schmutz gave participants a sequential planning canvas template that guided small-group product development module by module (target group, content, duration, pricing, marketing, sales), and also contributed as a digital/sales expert. The trainers: Peter Princzinger, Balint Erdei, Laszlo Szilasi, Peter Burgyan, Nikolett Hajdu, Adam Schmutz. Measurable result: the workshop produced a real, bookable experience package – a two-night Gen-Z (16–19 year-olds) Lake Balaton school trip at HUF 55,000/person, bookable online at balatonbiketour.com.",
    "type": "workshop",
    "typeLabel": "Workshop",
    "date": "2025-06-05 – 2025-06-06",
    "year": "2025",
    "location": "Keszthely, Hungary (VisitBalaton365 destination management training center)",
    "organizer": "VisitBalaton365 Nonprofit Ltd. (organizer). Trainers: Peter Princzinger, Balint Erdei, Laszlo Szilasi, Peter Burgyan, Nikolett Hajdu, Adam Schmutz (facilitator, digital tourism expert). With 20 Lake Balaton providers.",
    "tags": [
      "package offer",
      "product development",
      "experience package"
    ],
    "audience": "Lake Balaton tourism providers, travel agencies, accommodations, hospitality venues, experience providers",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "https://turizmus.com/cikk/kepzes/balatoni-elmenycsomagok-workshop-keszthely-visitbalaton365 ; https://turizmus.com/cikk/utazas/balaton-z-generacio-osztalykirandulas-csomagajanlat-visitbalaton365",
    "quote": "“From the program's facilitator, Adam Schmutz, we got a planning canvas template made of sequential parts that guided the thinking process and managed the time.” (Peter Burgyan, BalatonBikeTour – Turizmus.com) | Result: a real, bookable experience package (“Lake Balaton like you've never seen it!”) – a 26-person Gen-Z school trip at HUF 55,000/person, bookable at balatonbiketour.com.",
    "cover": "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-01.jpg",
    "photos": [
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-01.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-02.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-03.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-04.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-05.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-06.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-07.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-08.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-09.jpg",
      "/images/references/csomagajanlat-workshop-keszthely-2025/schmutz-adam-csomagajanlat-termekfejlesztes-workshop-keszthely-2025-10.jpg"
    ],
    "imageAlt": "01: Adam Schmutz giving a talk on package pricing at VisitBalaton365's Keszthely training center; in the foreground the “Package creation” canvas with participants' notes. 02: The Keszthely training room with the Lake Balaton map on the wall; participants at the two-day workshop, the title slide on the screen. 03: Small-group work next to the VisitBalaton365 banner and the projected canvas template. 04: Participants following a package example on the projector. 05: The Keszthely training room from above, participants at the U-shaped tables in front of the Lake Balaton map wall. 06: A small group working together on the package canvas. 07: Participants working over the package-planning template at the long table. 08: A lively discussion in a four-person group. 09: Workshop participants in a small-group consultation with notes and a canvas. 10: Participants at the training room table in front of the Lake Balaton map.",
    "seoTitle": "Package offer and product development workshop for Lake Balaton providers | VisitBalaton365",
    "seoDescription": "A two-day package offer and product development workshop in Keszthely with 20 Lake Balaton providers; Adam Schmutz facilitated – a real, bookable experience package was the result.",
    "featured": true,
    "order": 11,
    "size": "sm"
  },
  {
    "id": "16",
    "slug": "online-presence-strategy-workshop-dobosi-estate-2024",
    "title": "Online presence strategy workshop",
    "summary": "A hands-on online presence strategy workshop for 8 Lake Balaton providers at the Dobosi Estate: participants created their own strategy and a three-month plan. The proof that it works – one participant generated several hundred thousand forints in revenue from new online sales within a few months.",
    "description": "A one-day pilot online presence strategy workshop for experience-selling tourism providers at the Dobosi Estate Center (Szentantalfa). The four modules: (I) analyzing online visibility and online presence; (II) digital tools, online sales platforms and booking systems, conversion optimization; (III–IV) designing an online presence strategy. The presented tools were collected on a “link tree” (lnk.bio/novitatis), participants created their own strategy on a Figma whiteboard using a shared canvas framework, then chose 3 concrete projects achievable within three months (e.g. introducing online sales, increasing website traffic). The training was followed by individual online consultation. Measurable result: one participant launched online sales of their programs in a time-slot booking system and generated several hundred thousand forints in revenue.",
    "type": "workshop",
    "typeLabel": "Workshop",
    "date": "2024-02-23",
    "year": "2024",
    "location": "Dobosi Estate Center, Szentantalfa, Hungary",
    "organizer": "Online presence pilot training with 8 tourism providers. Venue: Dobosi Estate Center.",
    "tags": [
      "online presence strategy",
      "online sales",
      "booking system"
    ],
    "audience": "experience-selling tourism providers, SMEs, wineries, accommodations, hospitality venues (Lake Balaton)",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“Many similar trainings don't translate the professional message into the language of the average user... You found the common voice perfectly, so everyone could understand the information.” (Szilvia Mihaly, VisitBalaton365) | Result: one participant launched online sales in a time-slot booking system and generated several hundred thousand forints in revenue.",
    "cover": "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-01.jpg",
    "photos": [
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-01.jpg",
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-02.jpg",
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-03.jpg",
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-04.jpg",
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-05.jpg",
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-06.jpg",
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-07.jpg",
      "/images/references/online-jelenlet-workshop-dobosi-2024/schmutz-adam-online-jelenlet-workshop-dobosi-2024-08.jpg"
    ],
    "imageAlt": "01: The workshop room at the Dobosi Estate Center, participants working on laptops, the online presence material on the screen. 02: The Dobosi Estate Center workshop venue with participants at the long tables. 03: Tourism providers working on their own online presence strategy on laptops. 04: A workshop participant speaking up, with “DOBOS 1721” bottles and laptops on the table. 05: A participant presenting the projected online presence tool/canvas. 06: Group work, with workshop tools and diagrams on the participants' laptops. 07: Participants looking at an online booking system (Flokk) interface on the screen. 08: Adam Schmutz and participants building an online sales/booking interface (Kormoran water tour, HUF 31,500) at the Dobosi workshop.",
    "seoTitle": "Online presence strategy workshop for tourism providers | Lake Balaton",
    "seoDescription": "A one-day hands-on online presence and online sales workshop for 8 Lake Balaton tourism providers at the Dobosi Estate – strategy, booking system, measurable revenue.",
    "featured": true,
    "order": 12,
    "size": "wide"
  },
  {
    "id": "5",
    "slug": "digital-hospitality-balaton-website-analysis-book-chapter",
    "title": "Digital hospitality at Balaton: website study",
    "summary": "Research analyzing the websites of more than 1,300 Lake Balaton service providers, in a co-authored book chapter (Akadémiai Kiadó, “Changing Perspectives in Today's Tourism”). It maps the quality gaps of digital hospitality – joint work with University of Pannonia researchers, a cornerstone of our academic background.",
    "description": "Chapter 7 of the volume “Changing Perspectives in Today's Tourism” (ed. Mark Miskolczi, Akadémiai Kiadó, 2023), authored by Eszter Madarasz, Zsofia Marta Papp and Adam Schmutz (University of Pannonia, Faculty of Business and Economics, Department of Tourism). The chapter examines the role of digital marketing communication tools in tourism businesses in the context of the fourth industrial revolution. It analyzes the websites of more than 1,300 Lake Balaton service providers and highlights the quality problems that prevent some market players from meeting 21st-century consumer expectations. It discusses the role of an own website and presents good practices: as consumer pressure grows, Lake Balaton providers must follow digitalization trends and invest in their websites to stay competitive.",
    "type": "publication",
    "typeLabel": "Publication",
    "date": "2023",
    "year": "2023",
    "location": "Akadémiai Kiadó, Budapest (online edition, MeRSZ)",
    "organizer": "Changing Perspectives in Today's Tourism (ed. Mark Miskolczi), Akadémiai Kiadó, 2023 – Chapter 7. ISBN 978 963 454 973 4, ISSN 2732-1495",
    "tags": [
      "website analysis",
      "digital marketing communication",
      "Lake Balaton providers"
    ],
    "audience": "tourism service providers, researchers, students, destination managers",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "https://mersz.hu/miskolczi-valtozo-perspektivak-napjaink-turizmusaban/",
    "quote": "“The analysis of more than 1,300 Lake Balaton service provider websites shows that many market players' sites no longer meet 21st-century consumer expectations.”",
    "cover": "/images/manual-covers/book-chapter-2023.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "Digital hospitality at Lake Balaton – analysis of 1,300+ websites | book chapter",
    "seoDescription": "Adam Schmutz's co-authored book chapter: analysis of more than 1,300 Lake Balaton tourism providers' websites on the quality of digital hospitality.",
    "featured": true,
    "order": 2,
    "size": "sm"
  },
  {
    "id": "19",
    "slug": "digital-presence-tourinform-offices-national-tourinform-meeting-2023",
    "title": "Digital presence of Tourinform offices",
    "summary": "How do Tourinform offices perform in the digital space? A talk at the MTÜ National Tourinform Meeting (Villány): analysis of the online presence of 25 offices and the Visible Tourism concept – before the 94-office network, with press coverage (Turizmus.com).",
    "description": "At the professional conference of the MTÜ (Hungarian Tourism Agency / Visit Hungary) two-day National Tourinform Meeting (Villány, May 2023), Adam Schmutz gave a talk titled “The digital presence of Tourinform offices.” The talk analyzed the online presence of 25 Tourinform offices along six dimensions – access path (73%), information content (56%), visual appearance (43%), destination image (33%), social media (33%), functionality (19%) – as well as the digital visibility of Lake Balaton providers and the blocking points of the customer journey. The talk closed with the Visible Tourism concept and three key messages (visitor-centric mindset, development opportunities, Visible Tourism). Other speakers: Istvan Mayer (Mayor of Villány), Anita Molnar (Tourinform Coordination Office / Visit Hungary), Krisztian Steigervald (generation researcher), Renata Weinhardt (world café). The network participated with staff from 94 offices.",
    "type": "talk",
    "typeLabel": "Talk",
    "date": "2023-05-23",
    "year": "2023",
    "location": "Villány, Hungary (National Tourinform Meeting)",
    "organizer": "Hungarian Tourism Agency (MTÜ) / Visit Hungary – National Tourinform Meeting (two-day, 94 Tourinform offices). Speaker: Adam Schmutz (digital tourism expert, managing director).",
    "tags": [
      "Tourinform",
      "digital presence",
      "online visibility"
    ],
    "audience": "Tourinform office staff, destination management organizations, tourism decision-makers",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "https://turizmus.com/cikk/archiv/felkeszulten-varjak-a-foszezont-a-tourinformok-az-orszag-kozel-szaz-pontjan ; https://sumeginfo.hu/hirek-sumeg/orszagos-tourinform-talalkozo-ii-nap",
    "quote": "“Of the 25 Tourinform offices examined, the access path met modern expectations only 73% of the time, information content 56%, and functionality just 19% – this is where the Visible Tourism concept leads from.” (Adam Schmutz)",
    "cover": "/images/manual-covers/tourinform.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "The digital presence of Tourinform offices – talk | Adam Schmutz (National Tourinform Meeting)",
    "seoDescription": "Adam Schmutz's talk at the MTÜ National Tourinform Meeting in Villány: analysis of the Tourinform network's digital presence and the Visible Tourism concept.",
    "featured": false,
    "order": 19,
    "size": "sm"
  },
  {
    "id": "20",
    "slug": "digital-presence-balaton-providers-metu-checkinn-workshop-2023",
    "title": "Digital presence of Balaton providers",
    "summary": "The digital presence of Lake Balaton providers from the guest-experience perspective – a talk at the all-day Digital Tourism Workshop of Budapest Metropolitan University and CheckINN (~100 students, 11 talks). Focus on the blocking points of the customer journey; also covered by Turizmus.com.",
    "description": "At the joint, all-day Digital Tourism Workshop of the Tourism Institute of Budapest Metropolitan University (METU) and the CheckINN Tourism Innovation Hub (nearly 100 students, 11 talks and two round-table discussions), Adam Schmutz (managing director) gave a talk titled “The digital presence of Lake Balaton tourism destination providers, development opportunities.” He presented the digital presence of Lake Balaton providers from the guest-experience perspective and drew attention to the blocking points in the customer journey, whose handling is critical for the guest experience; he also took part in the workshop's round-table discussion. Other speakers included: Szabolcs Juhasz (MTÜ – NTAK), Noemi Ilyes (CheckINN), Noemi Kulcsar and Laszlo Vasa (METU), Zoltan Katona (Morgens), Peter Palicz (Kvi Hotel), Mark Miskolczi (Corvinus).",
    "type": "workshop",
    "typeLabel": "Workshop",
    "date": "2023-04-14",
    "year": "2023",
    "location": "Budapest, Hungary (Budapest Metropolitan University – METU)",
    "organizer": "Tourism Institute of Budapest Metropolitan University (METU) and CheckINN Tourism Innovation Hub (organizers) – Digital Tourism Workshop. Speaker: Adam Schmutz.",
    "tags": [
      "digital tourism",
      "online presence",
      "guest experience"
    ],
    "audience": "tourism students, tourism professionals, innovators, destination management",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "https://turizmus.com/cikk/archiv/metu-checkinn-workshop-a-digitalizacio-ma-mar-megkerulhetetlen-a-turizmusban",
    "quote": "“Adam Schmutz presented the digital presence of Lake Balaton tourism destination providers from the guest-experience perspective and drew attention to the blocking points in the customer journey, whose handling is critical for the guest experience.” (Turizmus.com)",
    "cover": "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-01.jpg",
    "photos": [
      "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-01.jpg",
      "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-02.jpg",
      "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-03.jpg",
      "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-04.jpg",
      "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-05.jpg",
      "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-06.jpg",
      "/images/references/digitalis-turizmus-workshop-metu-checkinn-2023/schmutz-adam-digitalis-turizmus-workshop-metu-checkinn-2023-07.jpg"
    ],
    "imageAlt": "01: Adam Schmutz speaking with a microphone in front of the CheckINN banner, with the audience in the foreground. 02: Adam Schmutz mid-talk, the CheckINN Tourism Innovation Hub banner in the background. 03: Adam Schmutz presenting to the workshop audience in front of the CheckINN backdrop. 04: The full lecture hall with the audience; Adam Schmutz on stage by the CheckINN banner. 05: Round-table discussion: Adam Schmutz and the moderator in front of the METU backdrop. 06: The participants of the workshop's round-table discussion in front of the Budapest Metropolitan University banner. 07: Adam Schmutz during a professional conversation in a break of the event.",
    "seoTitle": "The digital presence of Lake Balaton providers – talk | Adam Schmutz (METU × CheckINN)",
    "seoDescription": "Adam Schmutz's talk at the METU and CheckINN Digital Tourism Workshop: the digital presence of Lake Balaton providers and the customer-journey blocking points from the guest-experience perspective.",
    "featured": true,
    "order": 18,
    "size": "lg"
  },
  {
    "id": "18",
    "slug": "balaton365-season-opening-workshop-digital-visibility-2023",
    "title": "Balaton365 opener: digital visibility",
    "summary": "A discussion-starting research talk at the BalatonBike365 season-opening professional workshop (Budapest, Novotel): how visible are Lake Balaton providers in the digital space? Delivered before Lake Balaton decision-makers (MTSZA, MTÜ, Visit Hungary, BTSZ), this analysis is one of the starting points of our digital visibility work.",
    "description": "The opening, discussion-starting talk of the BalatonBike365 (BB365) season-opening professional workshop was given by Adam Schmutz, titled “The digital presence of Lake Balaton tourism destination providers, development opportunities.” The talk analyzed the digital visibility of Lake Balaton providers: based on a survey of 1,318 provider websites, the visitor (customer) journey gets stuck at some point for 92% of the providers examined (typical blocking points: foreign language, pricing, opening hours, booking option), and in the “100 good places / TOP 100” sample many have no working website at all. The talk closed with intervention recommendations pointing toward a SMART destination (improving the online accessibility of provider information, strengthening brand position, expanding online sales). The workshop served the four-season Lake Balaton concept; other speakers: Eszter Czene (MTÜ), Lajos Szabo (BB365), Peter Princzinger (BB365), Laszlo Konnyid (Quality Certification Body), Klara Wirth (Visit Hungary).",
    "type": "workshop",
    "typeLabel": "Workshop",
    "date": "2023-02-10",
    "year": "2023",
    "location": "Budapest, Hungary (Novotel Budapest City, Mozart I–II. hall)",
    "organizer": "BalatonBike365 (BB365) – Dr. Peter Princzinger, managing director (organizer). Season-opening workshop for the four-season Lake Balaton concept; invited: leaders of MTSZA, BB365, MTÜ, Visit Hungary, BTSZ.",
    "tags": [
      "digital visibility",
      "online presence",
      "website analysis"
    ],
    "audience": "tourism decision-makers, destination management, professional organizations (MTSZA, MTÜ, Visit Hungary, BTSZ), Lake Balaton providers",
    "language": "HU",
    "videoUrl": "",
    "pressUrl": "",
    "quote": "“For 92% of the 1,318 Lake Balaton provider websites examined, the visitor journey gets stuck at some point – one of the biggest barriers to the destination's online visibility.” (Adam Schmutz)",
    "cover": "/images/manual-covers/balaton365-season-opening.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "The digital visibility of Lake Balaton providers – keynote talk | Adam Schmutz",
    "seoDescription": "Adam Schmutz's season-opening research talk at the BalatonBike365 workshop: analysis of 1,318 Lake Balaton provider websites, blocking points and recommendations toward a SMART destination.",
    "featured": false,
    "order": 20,
    "size": "sm"
  },
  {
    "id": "22",
    "slug": "smart-balaton-podcast",
    "title": "SMART Balaton: Balaton's digital future",
    "summary": "What does a SMART, smart Lake Balaton look like? An audio piece on the vision of a digital, data-driven and more visible Lake Balaton destination – one episode of the two-part series linked to the “Digital Balaton” research. Available on SoundCloud.",
    "description": "Our own audio piece (Adam Schmutz), available on SoundCloud, on the SMART (smart) Lake Balaton concept: the role of digitalization, online visibility and a data-driven mindset in developing the Lake Balaton tourism destination. Together with the “Is Lake Balaton still analog?” episode it forms a two-part audio series linked to the “Digital Balaton” research.",
    "type": "podcast",
    "typeLabel": "Podcast",
    "date": "2023-02-09",
    "year": "2023",
    "location": "Online (SoundCloud)",
    "organizer": "Own podcast / audio – Adam Schmutz",
    "tags": [
      "SMART Balaton",
      "SMART tourism",
      "digitalization"
    ],
    "audience": "Lake Balaton tourism providers, destination management, decision-makers, interested listeners",
    "language": "HU",
    "videoUrl": "https://soundcloud.com/novitatis-consulting/smart-balaton",
    "pressUrl": "",
    "quote": "Q: What does the SMART Balaton look like? – The audio is about the vision of a digital, data-driven and more visible Lake Balaton destination.",
    "cover": "/images/manual-covers/smart-balaton.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "SMART Balaton – audio | Lake Balaton's smart, digital future",
    "seoDescription": "An audio piece on the SMART Balaton vision: digitalization, online visibility and a data-driven mindset in developing Lake Balaton tourism.",
    "featured": false,
    "order": 21,
    "size": "sm"
  },
  {
    "id": "21",
    "slug": "is-lake-balaton-still-analog-podcast",
    "title": "Is Lake Balaton still analog?",
    "summary": "How “analog” is Lake Balaton still in the digital space? An audio piece on the gaps in Lake Balaton providers' online presence and the direction of progress – the audio companion of the “Digital Balaton” research. Available on SoundCloud.",
    "description": "Our own audio piece (Adam Schmutz), available on SoundCloud, on the digital transformation of Lake Balaton. The episode explores the gaps in the online visibility of Lake Balaton tourism providers – closely linked to the “Digital Balaton” research (analysis of provider websites, the blocking points of the customer journey). Together with the “SMART Balaton” episode it forms a two-part audio series.",
    "type": "podcast",
    "typeLabel": "Podcast",
    "date": "2023-02-02",
    "year": "2023",
    "location": "Online (SoundCloud)",
    "organizer": "Own podcast / audio – Adam Schmutz",
    "tags": [
      "Lake Balaton",
      "digital presence",
      "online visibility"
    ],
    "audience": "Lake Balaton tourism providers, destination management, interested listeners",
    "language": "HU",
    "videoUrl": "https://soundcloud.com/novitatis-consulting/analog-meg-a-balaton",
    "pressUrl": "",
    "quote": "Q: How “analog” is Lake Balaton still in the digital space? – The audio explores the gaps in Lake Balaton providers' online presence and the direction of digital progress.",
    "cover": "/images/manual-covers/analog-balaton.jpg",
    "photos": [],
    "imageAlt": "",
    "seoTitle": "Is Lake Balaton still analog? – audio | digital presence at Lake Balaton",
    "seoDescription": "An audio piece on the digital presence of Lake Balaton tourism providers – how “analog” is Lake Balaton still in the online space?",
    "featured": false,
    "order": 22,
    "size": "wide"
  }
];
